name: instant_morfix
description: The simplest Morfix client

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^2.0.0
  rxdart: ^0.22.0
  http: ^0.11.3+16
  equatable: ^0.6.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/instant_morfix.png"

flutter:
  uses-material-design: true
  fonts:
  - family: Alef
    fonts:
    - asset: fonts/Alef-Regular.ttf
    - asset: fonts/Alef-Bold.ttf
      weight: 700
