name: instant_morfix
description: The simplest Morfix client

version: 0.0.1+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.19.0
  http: ^0.11.3+16
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/web_hi_res_512.png"

flutter:
  uses-material-design: true
  fonts:
  - family: Alef
    fonts:
    - asset: fonts/Alef-Regular.ttf
    - asset: fonts/Alef-Bold.ttf
      weight: 700
